var express = require('express');
var path = require('path');
var cookieParser = require('cookie-parser');
var logger = require('morgan');
var cors = require("cors")

var indexRouter = require('./routes/index');
var usersRouter = require('./routes/users');
var login=require('./routes/login');
var districtreg=require('./routes/districtreg');
var locationreg=require('./routes/locationreg');
var districtview=require('./routes/districtview');
var categoryreg=require('./routes/categoryreg');
var categoryview=require('./routes/categoryview');
var upload=require('./routes/upload'); 
var locationview=require('./routes/locationview'); 
var getdistrict=require('./routes/getdistrict'); 
var locationdelete=require('./routes/locationdelete'); 
var categorydelete=require('./routes/categorydelete'); 
var shopreg=require('./routes/shopreg'); 
var getcategorydetails=require('./routes/getcategorydetails'); 
var updatecategory=require('./routes/updatecategory'); 
var getlocationdetails=require('./routes/getlocationdetails'); 
var updatelocation=require('./routes/updatelocation'); 
var customerreg=require('./routes/customerreg'); 
var costumereg=require('./routes/costumereg'); 
var costumeview=require('./routes/costumeview'); 
var costumedelete=require('./routes/costumedelete'); 
var getcostumedetails=require('./routes/getcostumedetails'); 
var updatecostume=require('./routes/updatecostume'); 
var shopview=require('./routes/shopview'); 
var shopconfirm=require('./routes/shopconfirm'); 
var confirmedshopview=require('./routes/confirmedshopview'); 
var shopreject=require('./routes/shopreject'); 
var customerview=require('./routes/customerview'); 
var getshopdetails=require('./routes/getshopdetails'); 
var updateshop=require('./routes/updateshop'); 
var shopprofile=require('./routes/shopprofile'); 
var customerprofile=require('./routes/customerprofile'); 
var getcustomerdetails=require('./routes/getcustomerdetails'); 
var updatecustomer=require('./routes/updatecustomer'); 
var viewcostume=require('./routes/viewcostume'); 
var viewmorecostume=require('./routes/viewmorecostume'); 
var request=require('./routes/request'); 
var requestview=require('./routes/requestview');
var requestconfirm=require('./routes/requestconfirm');
var confirmedrequest=require('./routes/confirmedrequest');
var requestreject=require('./routes/requestreject');
var changestock=require('./routes/changestock');
var shopdetailsbyid=require('./routes/shopdetailsbyid');
var requestdetailsbyid=require('./routes/requestdetailsbyid');
var payment=require('./routes/payment');
var shopreport=require('./routes/shopreport');
var customerreport=require('./routes/customerreport');
var datewisereport=require('./routes/datewisereport');
var costumepie=require('./routes/costumepie');
var categorypie=require('./routes/categorypie');
var forgotpassword=require('./routes/forgotpassword');
var changepassword=require('./routes/changepassword');
var paymentview=require('./routes/paymentview');


var app = express();


app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

global.__basedir = path.resolve(path.dirname(''));

app.use('/', indexRouter);
app.use('/users', usersRouter);
app.use(cors());
app.use('/login',login);
app.use('/districtreg',districtreg);
app.use('/locationreg',locationreg);
app.use('/districtview',districtview);
app.use('/categoryreg',categoryreg);
app.use('/categoryview',categoryview);
app.use('/upload',upload);
app.use('/locationview',locationview);
app.use('/getdistrict',getdistrict);
app.use('/locationdelete',locationdelete);
app.use('/categorydelete',categorydelete);
app.use('/shopreg',shopreg);
app.use('/getcategorydetails',getcategorydetails);
app.use('/updatecategory',updatecategory);
app.use('/getlocationdetails',getlocationdetails);
app.use('/updatelocation',updatelocation);
app.use('/customerreg',customerreg);
app.use('/costumereg',costumereg);
app.use('/costumeview',costumeview);
app.use('/costumedelete',costumedelete);
app.use('/getcostumedetails',getcostumedetails);
app.use('/updatecostume',updatecostume);
app.use('/shopview',shopview);
app.use('/shopconfirm',shopconfirm);
app.use('/confirmedshopview',confirmedshopview);
app.use('/shopreject',shopreject);
app.use('/customerview',customerview);
app.use('/getshopdetails',getshopdetails);
app.use('/updateshop',updateshop);
app.use('/shopprofile',shopprofile);
app.use('/customerprofile',customerprofile);
app.use('/getcustomerdetails',getcustomerdetails);
app.use('/updatecustomer',updatecustomer);
app.use('/viewcostume',viewcostume);
app.use('/viewmorecostume',viewmorecostume);
app.use('/request',request);
app.use('/requestview',requestview);
app.use('/requestconfirm',requestconfirm);
app.use('/requestreject',requestreject);
app.use('/confirmedrequest',confirmedrequest);
app.use('/changestock',changestock);
app.use('/shopdetailsbyid',shopdetailsbyid);
app.use('/requestdetailsbyid',requestdetailsbyid);
app.use('/payment',payment);
app.use('/shopreport',shopreport);
app.use('/customerreport',customerreport);
app.use('/datewisereport',datewisereport);
app.use('/costumepie',costumepie);
app.use('/categorypie',categorypie);
app.use('/forgotpassword',forgotpassword);
app.use('/changepassword',changepassword);
app.use('/paymentview',paymentview);

module.exports = app;
